### ISSUE TITLE
Can you give more details about the Table1. in paper?

### ISSUE THREAD

**Issue by imzhangyd** [jfzhuang/IFR#1]
Thanks for your wonderful work. From Table 1, I think it shows that the CAC or CPS method using the remaining unlabeled frames for training has a significant performance improvement compared to not using them.  From 66.00 to 69.70, from 70.32 to 74.39. However, the paper says "no obvious improvement is gained.". Could you please explain that?
<img width="489" alt="Snipaste_2022-10-08_18-00-51" src="https://user-images.githubusercontent.com/39505533/194701968-89a7c031-7046-42af-a4e8-2ff0a6f5a41e.png">

**Comment by jfzhuang** [comment]
Thanks for your interest in our work. In Table 1, we found that using remaining frames can not bring significant performance gain when comparing to using sampled frames, e.g., 69.70 vs. 69.80. The result shows that existing SSIS methods can not further utilize unlabeled video frames when sampled frames is given. Therefore, in this work, we formulate a SSVS task and propose IFR to tackle this issue.

**Comment by imzhangyd** [comment]
Thanks for your answer, now I understand.😃

**Comment by imzhangyd** [comment]
Are the performance the result of testing on test split (1525 images) of  Cityscapes dataset? Or testing on every frame of the video?

**Comment by jfzhuang** [comment]
We followed a common practice to evaluate models on the val split (500 images) of Cityscapes. During the evaluation, we follow the protocol of Accel, which you can refer to.

**Comment by imzhangyd** [comment]
Okay, thanks a lot!
