### ISSUE TITLE
About the definition of semi-supervised.

### ISSUE THREAD

**Issue by imzhangyd** [jfzhuang/IFR#4]
Some VSS methods aggregate features of neighborhood unlabeled frames to segment the current frame, so I think these methods also use unlabeled frames for training and they can be considered semi-supervised. Did I misunderstand something here?

**Comment by jfzhuang** [comment]
Actually, I think the main challenge of semi-supervised learning is the model overfitting issue when given very limited labeled data, e.g., 100 samples in Cityscapes. Although existing methods are proposed to utilize unlabeled frames, they have utilized all labeled samples, e.g. 2975 samples in Cityscapes. Therefore, their models rarely suffer from the overfitting issue and only need to focus on boosting accuracy. In this aspect, I don't think these methods can be considered semi-supervised learning.

**Comment by Huster-Hq** [comment]
> Some VSS methods aggregate features of neighborhood unlabeled frames to segment the current frame, so I think these methods also use unlabeled frames for training and they can be considered semi-supervised. Did I misunderstand something here?

Can you provide me with some relevant papers?
